
1) Import the numpy package as np, so that you can refer to numpy with np.
Use np.array() to create a numpy array from baseball. Name this array np_baseball.
Print out the type of np_baseball to check that you got it right.


In [1]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(np_baseball)

[180 215 210 210 188 176 209 200]


In [2]:
type(np_baseball)

numpy.ndarray


2) Create a numpy array from height_in. Name this new array np_height_in.
Print np_height_in.
Multiply np_height_in with 0.0254 to convert all height measurements from inches to meters. Store the new values in a new array, np_height_m.
Print out np_height_m and check if the output makes sense.


In [3]:
# height is available as a regular list
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71]

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254
# Print np_height_m
np_height_m


[74 74 72 72 73 69 69 71 76 71]


array([1.8796, 1.8796, 1.8288, 1.8288, 1.8542, 1.7526, 1.7526, 1.8034,
       1.9304, 1.8034])

3) Create a numpy array from the weight_lb list with the correct units. Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as np_weight_kg.
Use np_height_m and np_weight_kg to calculate the BMI of each player. Use the following equation: 

${BMI} = \frac{\mathrm{weight (kg)}}{\mathrm{height (m)}^2}$

Save the resulting numpy array as bmi.
Print out bmi.

In [4]:
# height and weight are available as regular lists
height_in = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71]
weight_lb = [180, 215, 145, 210, 159, 176, 209, 200, 231, 180]

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) *  0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) *  0.453592


# Calculate the BMI: bmi
bmi = np.divide(np_weight_kg, np_height_m**2)

# Print out bmi
print(bmi)

[23.11037639 27.60406069 19.66531749 28.48080465 20.97728879 25.99036864
 30.86356276 27.89402921 28.11789135 25.10462629]



4) Create a boolean numpy array: the element of the array should be True if the corresponding baseball player's BMI is below 21. You can use the < operator for this. Name the array light.
Print the array light.
Print out a numpy array with the BMIs of all baseball players whose BMI is below 21. Use light inside square brackets to do a selection on the bmi array.


In [5]:
# Calculate the BMI: bmi
bmi = np.divide(np_weight_kg, np_height_m**2)

# Create the light array
light = bmi < 21

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[light])

[False False  True False  True False False False False False]
[19.66531749 20.97728879]



5) Subset np_weight_lb by printing out the element at index 5.
Print out a sub-array of np_height_in that contains the elements at index 5 up to and including index 10.


In [6]:
# Store weight and height lists as numpy arrays
weight = np.array(weight_lb)
height = np.array(height_in)

# Print out the weight at index 5
print(weight[5])

# Print out sub-array of np_height_in: index 5 up to and including index 10
weight[5:]


176


array([176, 209, 200, 231, 180])

6) Use np.array() to create a 2D numpy array from baseball. Name it np_baseball.
    Print out the type of np_baseball.
    Print out the shape attribute of np_baseball. Use np_baseball.shape.


In [7]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)


<class 'numpy.ndarray'>
(4, 2)


7) 
    Print out the 50th row of np_baseball.
    Make a new variable, np_weight_lb, containing the entire second column of np_baseball.
    Select the height (first column) of the 124th baseball player in np_baseball and print it out.


In [8]:
baseball = [[ 74, 180],
            [ 74, 215],
            [ 72, 210],
            [ 72, 210],
            [ 73, 188],
            [ 69, 176],
            [ 69, 209],
            [ 71, 200],
            [ 76, 231],
            [ 71, 180],
            [ 73, 188],
            [ 73, 180],
            [ 74, 185],
            [ 74, 160],
            [ 69, 180],
            [ 70, 185],
            [ 73, 189],
            [ 75, 185],
            [ 78, 219],
            [ 79, 230]]

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 20th row of np_baseball
print(np_baseball[19:])

# Select the entire second column of np_baseball: np_weight_lb
all_heights = np_baseball[: , 1]

# Print out height of 12th player
all_heights[11]

[[ 79 230]]


180

8) 
    You managed to get hold of the changes in height, weight and age of all baseball players. It is available as a 2D numpy array, updated. Add np_baseball and updated and print out the result.
    You want to convert the units of height and weight to metric (meters and kilograms, respectively). As a first step, create a numpy array with three values: 0.0254, 0.453592 and 1. Name this array conversion.
    Multiply np_baseball with conversion and print out the result.


In [9]:
# baseball is available as a regular list of lists
# updated is available as 2D numpy array
baseball = [[ 74.  , 180.  ,  22.99],
       [ 74.  , 215.  ,  34.69],
       [ 72.  , 210.  ,  30.78],
       [ 72.  , 210.  ,  35.43],
       [ 73.  , 188.  ,  35.71],
       [ 69.  , 176.  ,  29.39],
       [ 69.  , 209.  ,  30.77],
       [ 71.  , 200.  ,  35.07],
       [ 76.  , 231.  ,  30.19],
       [ 71.  , 180.  ,  27.05],
       [ 73.  , 188.  ,  23.88],
       [ 73.  , 180.  ,  26.96],
       [ 74.  , 185.  ,  23.29],
       [ 74.  , 160.  ,  26.11],
       [ 69.  , 180.  ,  27.55],
       [ 70.  , 185.  ,  34.27],
       [ 73.  , 189.  ,  27.99],
       [ 75.  , 185.  ,  22.38],
       [ 78.  , 219.  ,  22.89],
       [ 79.  , 230.  ,  25.76]]
updated = np.array([[  1.2303559 , -11.16224898,   1.        ],
       [  1.02614252,  16.09732309,   1.        ],
       [  1.1544228 ,   5.08167641,   1.        ],
       [  0.64427532,  -5.09538071,   1.        ],
       [  1.00590086,   2.24342718,   1.        ],
       [  0.97953547,  12.19841763,   1.        ],
       [  0.62874324,  13.72324216,   1.        ],
       [  1.27075194,  -8.87946313,   1.        ],
       [  0.47655945, -10.82495536,   1.        ],
       [  0.91699376,  -7.01116249,   1.        ],
       [  1.17179326,   1.19946614,   1.        ],
       [  1.14509104, -12.00385685,   1.        ],
       [  1.20684945, -13.29830645,   1.        ],
       [  1.03436155,   3.01324251,   1.        ],
       [  0.87747454,  10.51779503,   1.        ],
       [  0.9813308 ,  -1.55666485,   1.        ],
       [  1.03051228,   4.47971582,   1.        ],
       [  1.21042271, -19.04502745,   1.        ],
       [  1.34612414,   6.74418894,   1.        ],
       [  0.97544726,   7.27211497,   1.        ]])

# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1])

# Print out product of np_baseball and conversion
np_baseball * conversion

[[ 75.2303559  168.83775102  23.99      ]
 [ 75.02614252 231.09732309  35.69      ]
 [ 73.1544228  215.08167641  31.78      ]
 [ 72.64427532 204.90461929  36.43      ]
 [ 74.00590086 190.24342718  36.71      ]
 [ 69.97953547 188.19841763  30.39      ]
 [ 69.62874324 222.72324216  31.77      ]
 [ 72.27075194 191.12053687  36.07      ]
 [ 76.47655945 220.17504464  31.19      ]
 [ 71.91699376 172.98883751  28.05      ]
 [ 74.17179326 189.19946614  24.88      ]
 [ 74.14509104 167.99614315  27.96      ]
 [ 75.20684945 171.70169355  24.29      ]
 [ 75.03436155 163.01324251  27.11      ]
 [ 69.87747454 190.51779503  28.55      ]
 [ 70.9813308  183.44333515  35.27      ]
 [ 74.03051228 193.47971582  28.99      ]
 [ 76.21042271 165.95497255  23.38      ]
 [ 79.34612414 225.74418894  23.89      ]
 [ 79.97544726 237.27211497  26.76      ]]


array([[  1.8796  ,  81.64656 ,  22.99    ],
       [  1.8796  ,  97.52228 ,  34.69    ],
       [  1.8288  ,  95.25432 ,  30.78    ],
       [  1.8288  ,  95.25432 ,  35.43    ],
       [  1.8542  ,  85.275296,  35.71    ],
       [  1.7526  ,  79.832192,  29.39    ],
       [  1.7526  ,  94.800728,  30.77    ],
       [  1.8034  ,  90.7184  ,  35.07    ],
       [  1.9304  , 104.779752,  30.19    ],
       [  1.8034  ,  81.64656 ,  27.05    ],
       [  1.8542  ,  85.275296,  23.88    ],
       [  1.8542  ,  81.64656 ,  26.96    ],
       [  1.8796  ,  83.91452 ,  23.29    ],
       [  1.8796  ,  72.57472 ,  26.11    ],
       [  1.7526  ,  81.64656 ,  27.55    ],
       [  1.778   ,  83.91452 ,  34.27    ],
       [  1.8542  ,  85.728888,  27.99    ],
       [  1.905   ,  83.91452 ,  22.38    ],
       [  1.9812  ,  99.336648,  22.89    ],
       [  2.0066  , 104.32616 ,  25.76    ]])

9) 
    Create numpy array np_height_in that is equal to first column of np_baseball.
    Print out the mean of np_height_in.
    Print out the median of np_height_in.


In [10]:
import numpy as np
# np_baseball is available
np_baseball = np.array([[ 74.  , 180.  ,  22.99],
       [ 74.  , 215.  ,  34.69],
       [ 72.  , 210.  ,  30.78],
       [ 72.  , 210.  ,  35.43],
       [ 73.  , 188.  ,  35.71],
       [ 69.  , 176.  ,  29.39],
       [ 69.  , 209.  ,  30.77],
       [ 71.  , 200.  ,  35.07],
       [ 76.  , 231.  ,  30.19],
       [ 71.  , 180.  ,  27.05],
       [ 73.  , 188.  ,  23.88],
       [ 73.  , 180.  ,  26.96],
       [ 74.  , 185.  ,  23.29],
       [ 74.  , 160.  ,  26.11],
       [ 69.  , 180.  ,  27.55],
       [ 70.  , 185.  ,  34.27],
       [ 73.  , 189.  ,  27.99],
       [ 75.  , 185.  ,  22.38],
       [ 78.  , 219.  ,  22.89],
       [ 79.  , 230.  ,  25.76]])

# Create np_height_in from np_baseball
np_height_in = np_baseball[:, 0]

# Print out the mean of np_height_in
print(np_height_in.mean())
# Print out the median of np_height_in
np.median(np_height_in)

72.95


73.0

10) 
    The code to print out the mean height is already included. Complete the code for the median height. Replace None with the correct code.
    Use np.std() on the first column of np_baseball to calculate stddev. Replace None with the correct code.
    Do big players tend to be heavier? Use np.corrcoef() to store the correlation between the first and second column of np_baseball in corr. Replace None with the correct code.


In [11]:
# np_baseball is available
np_baseball = np.array([[ 74.  , 180.  ,  22.99],
       [ 74.  , 215.  ,  34.69],
       [ 72.  , 210.  ,  30.78],
       [ 72.  , 210.  ,  35.43],
       [ 73.  , 188.  ,  35.71],
       [ 69.  , 176.  ,  29.39],
       [ 69.  , 209.  ,  30.77],
       [ 71.  , 200.  ,  35.07],
       [ 76.  , 231.  ,  30.19],
       [ 71.  , 180.  ,  27.05],
       [ 73.  , 188.  ,  23.88],
       [ 73.  , 180.  ,  26.96],
       [ 74.  , 185.  ,  23.29],
       [ 74.  , 160.  ,  26.11],
       [ 69.  , 180.  ,  27.55],
       [ 70.  , 185.  ,  34.27],
       [ 73.  , 189.  ,  27.99],
       [ 75.  , 185.  ,  22.38],
       [ 78.  , 219.  ,  22.89],
       [ 79.  , 230.  ,  25.76]])

players_height = np_baseball[:, 0]
players_weight = np_baseball[:, 1]
# Print mean height (first column)
avg = players_height.mean()
print("Average: " + str(avg))

# Print median height. 
med = np.median(players_height)
print("Median: " + str(med))

# Print out the standard deviation on height. 
stddev = np.std(players_height)
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. 
corr = np.corrcoef(players_height, players_weight)
print("Correlation: " + str(corr))

Average: 72.95
Median: 73.0
Standard Deviation: 2.692118125194361
Correlation: [[1.         0.47158169]
 [0.47158169 1.        ]]
